#!/bin/sh
BUILD_DIR='./build'
if [ -d ${BUILD_DIR} ]; then
    if [ "$1" = "new" ]; then
	    rm -rf ${BUILD_DIR}
    else
        ninja -C ${BUILD_DIR} && exit
    fi
fi
meson . ${BUILD_DIR} \
          -Dbuildtype=debug \
          -Denable_tests=true \
          -Denable_traces=true \
          && ninja -C ${BUILD_DIR}
